## Prod Version

# name and version of parent image
FROM node:4.6.1

# name of maintainer
MAINTAINER JanBrnak

# set arguments
ARG api_host=127.0.0.1
ARG api_port=3333

# global ENV variables
ENV ENV=dev \
	PORT=3000 \
	OG_HOST=$api_host \
	OG_PORT=$api_port

# list of ports
EXPOSE 3000

# workdir in the container
WORKDIR /usr/src/app

# VOLUME
# VOLUME $PWD:/usr/src/app

# run commands in the image
RUN apt-get update --yes \
	&& apt-get upgrade --yes \
	&& npm install -g gulp-cli \
	&& npm install -g bower

# copy/paste only package.json/bower.json in the workdir
COPY package.json .
COPY bower.json .

# run commands in the image and install node dependencies
RUN bower install --allow-root --force-latest && npm install

# copy/paste all folders/files in the workdir
COPY . .

# run command in the container
# CMD gulp serve

# Build image: docker build --build-arg=api_host=127.0.0.1 --build-arg=api_port=3333 --tag=pa_front-end-dev:latest --file=Dockerfile.dev .
# Create container: docker run --detach --publish=3000:3000 --name=pa-fe-dev pa_front-end-dev:latest
# Create container: docker run --interactive --tty --publish=3000:3000 --volume=$PWD:/usr/src/app --name=pa-fe-dev pa_front-end-dev:latest /bin/bash -c 'npm start'
# Connect to container: docker exec --interactive --tty pa-fe-dev /bin/bash