## Prod Version

# name and version of parent image
FROM nginx:latest

# name of maintainer
MAINTAINER JanBrnak

# set arguments
ARG api_host=127.0.0.1
ARG api_port=3333

# list of ports
EXPOSE 3000

# workdir in the container
WORKDIR /usr/src/app

# run commands in the image
RUN apt-get update --yes \
	&& apt-get upgrade --yes


# copy/paste all folders/files in the workdir
COPY ./dist .

# copy/paste nginx.conf
COPY ./nginx.conf /etc/nginx/

# service nginx start/stop/restart/status