## Dev Version

# name and version of parent image
FROM node:latest

# name of maintainer
MAINTAINER JanBrnak

# set arguments
ARG og_host=127.0.0.1
ARG og_port=8080

# global ENV variables
ENV ENV=dev \
	PORT=3333 \
	OG_HOST=80.241.212.28 \
	OG_PORT=8080

# list of ports
EXPOSE 3333 \
	9229

# workdir in the container
WORKDIR /usr/src/app

# map voluem folder
# VOLUME $PWD:/usr/src/app

# run commands in the image
RUN apt-get update --yes \
	&& apt-get upgrade --yes \
	&& npm install -g nodemon

# CMD npm run dev
# CMD npm run dev-brk

# Build image: sudo docker build --build-arg=og_host=80.241.212.28 --build-arg=og_port=8080 --tag=pa_back-end-dev:latest --file=Dockerfile.dev .
# Create container: sudo docker run --interactive --tty --volume=$PWD:/usr/src/app --publish=3333:3333 --publish=9229:9229 --name=pa-be-dev pa_back-end-dev:latest /bin/bash -c 'npm install'
# Connect to container: sudo docker exec --interactive --tty my-app-dev /bin/bash