## Dev Version

# name and version of parent image
FROM node:latest

# name of maintainer
MAINTAINER JanBrnak

# set arguments
ARG og_host=127.0.0.1
ARG og_port=8080

# global ENV variables
ENV ENV=dev \
	PORT=3333 \
	OG_HOST=192.168.0.55 \
	OG_PORT=8090

# list of ports
EXPOSE 3333 \
	9229

# workdir in the container
WORKDIR /usr/src/app

# map voluem folder
# VOLUME $PWD:/usr/src/app

# run commands in the image
RUN apt-get update --yes \
	&& apt-get upgrade --yes \
	&& npm install -g nodemon

# CMD npm run dev
# CMD npm run dev-brk

# Build image: docker build --build-arg=og_host=192.168.0.55 --build-arg=og_port=8090 --tag=my-app-dev:latest --file=Dockerfile.dev .
# Create container: docker run --interactive --tty --volume=$PWD:/usr/src/app --publish=3333:3333 --publish=9229:9229 --name=my-app-dev my-app-dev:latest /bin/bash -c 'npm install'
# Connect to container: docker exec --interactive --tty my-app-dev /bin/bash